export enum EResponseError {
  VALIDATION_ERROR = "VALIDATION_ERROR",
  AUTHENTICATION_ERROR = "AUTHENTICATION_ERROR",
  FORBIDDEN_ERROR = "FORBIDDEN_ERROR",
  NOT_FOUND_ERROR = "NOT_FOUND_ERROR",
  METHOD_NOT_ALLOWED = "METHOD_NOT_ALLOWED",
  BAD_REQUEST = "BAD_REQUEST",
  SERVER_ERROR = "SERVER_ERROR",
  SERVICE_UNAVAILABLE = "SERVICE_UNAVAILABLE",
  TIMEOUT_ERROR = "TIMEOUT_ERROR",
  NETWORK_ERROR = "NETWORK_ERROR",
  UNKNOWN_ERROR = "UNKNOWN_ERROR",
}

export enum ECardType {
  CREDIT = "Creditcard",
  DEBIT = "DebitCard",
}


export enum EBrandCard {
  MASTERCARD = "MASTER", 
  VISA = "VISA",
  AMEX = "AMEX",
  ELO = "ELO",
  HIPERCARD = "HIPERCARD",
  DINERS = "DINERS",
  DISCOVER = "DISCOVER",
  JCB = "JCB",
}